name: Build and publish container
on:
  push:
    branches:
      - main
jobs:
  docker_publish:
    permissions:
      contents: read
      packages: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
